version: '3.8'
services:
  db: 
    image: postgres:15
    restart: unless-stopped
    container_name: crucero_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: erick17
      POSTGRES_DB: crucero_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: